version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "10"
    max-size: "1M"

x-mysql-environment:
  &mysql-environment
  MYSQL_ROOT_PASSWORD: rut
  MYSQL_DATABASE: myExampleDB
  MYSQL_USER: exampleUser
  MYSQL_PASSWORD: secretUserPassword
  MYSQL_REPL_USER: repl
  MYSQL_REPL_PASSWORD: replic8

networks:
  default:
    name: marias-playground

services:
  mysql1:
    image: mariadb:10.7
    container_name: mysql1
    command: --default-authentication-plugin=mysql_native_password --datadir=/var/lib/mysql --log-bin=mysql-bin --binlog_format=ROW --expire_logs_days=10 --key_buffer_size=16M --max_allowed_packet=16M --max_binlog_size=500M --server-id=1 --auto_increment_offset=1 --auto_increment_increment=2 --binlog_do_db=myExampleDB
    environment:
      MYSQL_REPL_MASTER: mysql2
      <<: *mysql-environment
    logging: *default-logging
    ports:
      - "3306:3306"
    volumes:
      - mysql1:/var/lib/mysql
      - ./env/mysql/:/docker-entrypoint-initdb.d/
  mysql2:
    image: mariadb:10.7
    container_name: mysql2
    command: --default-authentication-plugin=mysql_native_password --datadir=/var/lib/mysql --log-bin=mysql-bin --binlog_format=ROW --expire_logs_days=10 --key_buffer_size=16M --max_allowed_packet=16M --max_binlog_size=500M --server-id=2 --auto_increment_offset=1 --auto_increment_increment=2 --binlog_do_db=myExampleDB
    environment:
      MYSQL_REPL_MASTER: mysql1
      <<: *mysql-environment
    logging: *default-logging
    ports:
      - "3307:3306"
    volumes:
      - mysql2:/var/lib/mysql
      - ./env/mysql/:/docker-entrypoint-initdb.d/

volumes:
  mysql1:
  mysql2:
