#!/bin/sh -x

create_database_and_user() {
    DB=$1
    USER=$2
    PASSWORD=$3

    mysql --user root --password=$MYSQL_ROOT_PASSWORD <<EOS
CREATE DATABASE IF NOT EXISTS ${DB};
CREATE USER IF NOT EXISTS  '${USER}'@'%' IDENTIFIED BY '${PASSWORD}';
GRANT ALL ON ${DB}.* TO '${USER}'@'%';
EOS
}

create_database_and_user ${MYSQL_DATABASE} ${MYSQL_USER} ${MYSQL_PASSWORD}

mysql --user root --password=$MYSQL_ROOT_PASSWORD <<EOS
GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPL_USER}'@'%' IDENTIFIED BY '${MYSQL_REPL_PASSWORD}';
RESET MASTER;
DO SLEEP(3);
CHANGE MASTER TO MASTER_HOST='${MYSQL_REPL_MASTER}', MASTER_USER='${MYSQL_REPL_USER}', MASTER_PASSWORD='${MYSQL_REPL_PASSWORD}'; 
START SLAVE;
SHOW SLAVE STATUS\G
EOS

